// Generated by gencpp from file gazebo_ros_link_attacher/Gripper.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_LINK_ATTACHER_MESSAGE_GRIPPER_H
#define GAZEBO_ROS_LINK_ATTACHER_MESSAGE_GRIPPER_H

#include <ros/service_traits.h>


#include <gazebo_ros_link_attacher/GripperRequest.h>
#include <gazebo_ros_link_attacher/GripperResponse.h>


namespace gazebo_ros_link_attacher
{

struct Gripper
{

typedef GripperRequest Request;
typedef GripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gripper
} // namespace gazebo_ros_link_attacher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ros_link_attacher::Gripper > {
  static const char* value()
  {
    return "b6ef517238124133d1f6964a49370da8";
  }

  static const char* value(const ::gazebo_ros_link_attacher::Gripper&) { return value(); }
};

template<>
struct DataType< ::gazebo_ros_link_attacher::Gripper > {
  static const char* value()
  {
    return "gazebo_ros_link_attacher/Gripper";
  }

  static const char* value(const ::gazebo_ros_link_attacher::Gripper&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ros_link_attacher::GripperRequest> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::Gripper >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::GripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::Gripper >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::GripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::GripperRequest> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::Gripper >
template<>
struct DataType< ::gazebo_ros_link_attacher::GripperRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::Gripper >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::GripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ros_link_attacher::GripperResponse> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::Gripper >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::GripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::Gripper >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::GripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::GripperResponse> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::Gripper >
template<>
struct DataType< ::gazebo_ros_link_attacher::GripperResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::Gripper >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::GripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_ROS_LINK_ATTACHER_MESSAGE_GRIPPER_H
