// Generated by gencpp from file gazebo_ros_link_attacher/GripperRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_LINK_ATTACHER_MESSAGE_GRIPPERREQUEST_H
#define GAZEBO_ROS_LINK_ATTACHER_MESSAGE_GRIPPERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_ros_link_attacher
{
template <class ContainerAllocator>
struct GripperRequest_
{
  typedef GripperRequest_<ContainerAllocator> Type;

  GripperRequest_()
    : activate_gripper(false)  {
    }
  GripperRequest_(const ContainerAllocator& _alloc)
    : activate_gripper(false)  {
  (void)_alloc;
    }



   typedef uint8_t _activate_gripper_type;
  _activate_gripper_type activate_gripper;





  typedef boost::shared_ptr< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GripperRequest_

typedef ::gazebo_ros_link_attacher::GripperRequest_<std::allocator<void> > GripperRequest;

typedef boost::shared_ptr< ::gazebo_ros_link_attacher::GripperRequest > GripperRequestPtr;
typedef boost::shared_ptr< ::gazebo_ros_link_attacher::GripperRequest const> GripperRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator1> & lhs, const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator2> & rhs)
{
  return lhs.activate_gripper == rhs.activate_gripper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator1> & lhs, const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_ros_link_attacher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "923c733a75af78e3834068ddb1235791";
  }

  static const char* value(const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x923c733a75af78e3ULL;
  static const uint64_t static_value2 = 0x834068ddb1235791ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ros_link_attacher/GripperRequest";
  }

  static const char* value(const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool activate_gripper\n"
;
  }

  static const char* value(const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.activate_gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ros_link_attacher::GripperRequest_<ContainerAllocator>& v)
  {
    s << indent << "activate_gripper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.activate_gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_ROS_LINK_ATTACHER_MESSAGE_GRIPPERREQUEST_H
